Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.vagrant_vagrantfile = "../host/Vagrantfile"
    d.vagrant_machine = "host1"
    d.build_dir = "../host/Dockerfile/"
    d.has_ssh = false
    d.env = {DC: "dc1", JOIN: "192.168.10.11"}
  end

  config.vm.define "dc1-db" do |db|
    db.vm.hostname = "dc1-db"
  end
  (1..3).each do |i|
    config.vm.define vm_name = "dc1-web0%01d" % i do |web|
      web.vm.hostname = "#{vm_name}"
    end
  end
end
