Vagrant.configure("2") do |config|
  ["192.168.11.11", "192.168.12.12"].to_enum.with_index(1).each do |ip, dc|
    (1..2).each do |i|
      config.vm.define vm_name = "dc#{dc}-consul%01d" % i do |consul|
        consul.vm.hostname = "#{vm_name}"
        consul.vm.provider "docker" do |d|
          d.vagrant_vagrantfile = "../host/Vagrantfile"
          d.vagrant_machine = "host#{dc}"
          d.build_dir = "../host/Dockerfile-consul/"
          d.has_ssh = false
          d.env = {DC: "dc#{dc}", JOIN: ip}
        end
      end
    end
  end
end
