Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.vagrant_vagrantfile = "../host/Vagrantfile"
    d.vagrant_machine = "host1"
    d.build_dir = "../host/Dockerfile-consul/"
    d.has_ssh = false
    d.env = {DC: "dc1", JOIN: "192.168.11.11"}
  end

  (1..2).each do |i|
    config.vm.define vm_name = "dc1-consul%01d" % i do |consul|
      consul.vm.hostname = "#{vm_name}"
    end
  end
end
