Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.vagrant_vagrantfile = "../host/Vagrantfile"
    d.vagrant_machine = "host2"
    d.build_dir = "Dockerfile/"
    d.has_ssh = false
    d.env = {DC: "dc2", JOIN: "192.168.10.12"}
  end

  config.vm.define "dc2-db" do |db|
    db.vm.hostname = "dc2-db"
  end
  (1..3).each do |i|
    config.vm.define vm_name = "dc2-web0%01d" % i do |web|
      web.vm.hostname = "#{vm_name}"
    end
  end
end
