# -*- mode: ruby -*-
# vi: set ft=ruby :

#configuration of host resolv
$resolv = <<-EOF
cat > /etc/resolv.conf <<EOF2
search consul node.dc1.consul node.dc2.consul
nameserver 192.168.10.11
nameserver 192.168.10.12
nameserver 10.0.2.3
EOF2
EOF

#download and uncompress of consul tools
$consul = <<-EOF
CONSULZIP=0.4.1_linux_amd64.zip
CONSULUIZIP=0.4.1_web_ui.zip
CONSULTEMPLATETAR=consul-template_0.1.0_linux_amd64.tar.gz
cd /vagrant/
[ -f $CONSULZIP ] || wget -N https://dl.bintray.com/mitchellh/consul/$CONSULZIP 2>&1
[ -f $CONSULUIZIP ] || wget -N https://dl.bintray.com/mitchellh/consul/$CONSULUIZIP 2>&1
[ -f $CONSULTEMPLATETAR ] || wget -N https://github.com/hashicorp/consul-template/releases/download/v0.1.0/$CONSULTEMPLATETAR 2>&1
unzip -n /vagrant/$CONSULZIP -d /usr/local/bin/
unzip -n /vagrant/$CONSULUIZIP -d /usr/local/ui/
tar zxf /vagrant/$CONSULTEMPLATETAR -C /usr/local/bin/ --strip-components=1
EOF

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.configure("2") do |config|
  config.vm.box = "kikitux/oracle6"
  # Virtualbox configuration, network settings required to allow docker container traffic between host vms
  config.vm.provider "virtualbox" do |vb|
  # vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize ["modifyvm", :id, "--nictype3", "Am79C973"]
  end

  #enable daemon and start docker service
  #docker0 bridge will be on eth2 network
  config.vm.provision "shell", inline: "cp /vagrant/ifcfg-docker0.$HOSTNAME /etc/sysconfig/network-scripts/ifcfg-docker0"
  config.vm.provision "shell", inline: "cp /vagrant/ifcfg-eth2.$HOSTNAME /etc/sysconfig/network-scripts/ifcfg-eth2"
  config.vm.provision "shell", inline: "ifup eth2 2>&1 ; ifup docker0 2>&1"
  #docker service
  config.vm.provision "shell", inline: "chkconfig docker on"
  config.vm.provision "shell", inline: "service docker status || service docker start"
  #to avoid resolv.conf to be overwritten
  config.vm.provision "shell", inline: "grep PEERDNS /etc/sysconfig/network-scripts/ifcfg-eth0 || echo PEERDNS=no >> /etc/sysconfig/network-scripts/ifcfg-eth0"
  config.vm.provision "shell", inline: $resolv
  #installation of consul
  config.vm.provision "shell", inline: $consul
  #configure dnsmasq to use consul zone
  config.vm.provision "shell", inline: "grep consul /etc/dnsmasq.conf || (echo 'server=/consul/127.0.0.1#8600' | tee -a /etc/dnsmasq.conf && service dnsmasq force-reload)"
  #docker build to warn-up these images, so provision will be faster
  config.vm.provision "shell", inline: "for DF in /vagrant/Dockerfile* ; do docker build --tag docker${DF#/vagrant/Dockerfile} $DF/; done 2>&1"
  #ensure haproxy and nginx are installed and running
  config.vm.provision "shell", inline: "rpm -q nginx haproxy || yum install -y nginx haproxy"
  config.vm.provision "shell", inline: "chkconfig nginx on; cp -f /vagrant/nginx.conf /etc/nginx/ ; service nginx restart"
  config.vm.provision "shell", inline: "chkconfig haproxy on ; service haproxy restart"

  config.vm.define "host1" do |host1|
    host1.vm.hostname = "host1"
    host1.vm.network "private_network", ip: "192.168.10.11"
    host1.vm.network "private_network", ip: "192.168.11.11", auto_config: false
    host1.vm.network "forwarded_port", guest: 80, host: 8001
    host1.vm.network "forwarded_port", guest: 8000, host: 8081
    #run consul if not running
    host1.vm.provision "shell", run: "always", inline: "/usr/local/bin/consul members || /usr/local/bin/consul agent -bind=192.168.11.11 -dc=dc1 -bootstrap-expect=1 -server -data-dir=/var/tmp/consul -ui-dir=/usr/local/ui/dist -config-dir=/vagrant/consul-checks 2>&1 >> /vagrant/consul_$HOSTNAME.log & "
  end

  config.vm.define "host2" do |host2|
    host2.vm.hostname = "host2"
    host2.vm.network "private_network", ip: "192.168.10.12"
    host2.vm.network "private_network", ip: "192.168.12.12", auto_config: false
    host2.vm.network "forwarded_port", guest: 80, host: 8002
    host2.vm.network "forwarded_port", guest: 8000, host: 8082
    host2.vm.provision "shell", run: "always", inline: "/usr/local/bin/consul members || /usr/local/bin/consul agent -bind=192.168.12.12 -dc=dc2 -bootstrap-expect=1 -server -data-dir=/var/tmp/consul -ui-dir=/usr/local/ui/dist -config-dir=/vagrant/consul-checks 2>&1 >> /vagrant/consul_$HOSTNAME.log & "
  end

  #make consul join the other host over wan
  config.vm.provision "shell", run: "always", inline: "([ ${HOSTNAME#host} -eq 2 ] && /usr/local/bin/consul join -wan 192.168.11.11 || /usr/local/bin/consul join -wan 192.168.12.12) || true "

end
